const presets = {
  'Default': {
      speed: 1.0,
      iterations: 8,
      scale: 0.2,
      dotFactor: 0.7,
      vOffset: 0.7,
      intensityFactor: 0.2,
      expFactor: 4.0,
      redFactor: 1.0,
      greenFactor: -1.0,
      blueFactor: -2.0,
      colorShift: 0.0,
  },
  'Cosmic Waves': {
      speed: 0.8,
      iterations: 10,
      scale: 0.15,
      dotFactor: 0.9,
      vOffset: 0.5,
      intensityFactor: 0.25,
      expFactor: 5.0,
      redFactor: 0.5,
      greenFactor: -0.8,
      blueFactor: -1.5,
      colorShift: 0.2,
  },
  'Solar Flare': {
      speed: 2.2,
      iterations: 7,
      scale: 0.11,
      dotFactor: 0.32,
      vOffset: 10.0,
      intensityFactor: 0.12,
      expFactor: 12.0,
      redFactor: 1.8,
      greenFactor: 0.4,
      blueFactor: -0.4,
      colorShift: 0.0,
  },
  'Deep Ocean': {
      speed: 0.6,
      iterations: 12,
      scale: 0.25,
      dotFactor: 0.8,
      vOffset: 0.6,
      intensityFactor: 0.15,
      expFactor: 4.5,
      redFactor: -1.2,
      greenFactor: -0.2,
      blueFactor: 1.5,
      colorShift: 0.3,
  },
  'The Matrix': {
      speed: 1.2,
      iterations: 8,
      scale: 0.18,
      dotFactor: 0.75,
      vOffset: 0.9,
      intensityFactor: 0.22,
      expFactor: 6.0,
      redFactor: -1.5,
      greenFactor: 1.8,
      blueFactor: -1.5,
      colorShift: 0.1,
  },
  'Knot': {
      speed: 2.3,
      iterations: 4,
      scale: 0.04,
      dotFactor: 0.31,
      vOffset: 1.14,
      intensityFactor: 0.08,
      expFactor: 3.7,
      redFactor: 0.3,
      greenFactor: 0.0,
      blueFactor: 0.1,
      colorShift: 0,
  }
};