const presets = {
    'Liquid': {
        speed: 2.2,
        iterations: 13,
        scale: 0.05,
        dotFactor: 0.1,
        vOffset: 6.4,
        intensityFactor: 0.23,
        expFactor: 0.6,
        redFactor: 0,
        greenFactor: 0,
        blueFactor: 0,
        colorShift: 1.0,
    },
    'Horizon': {
      speed: 0.7,
      iterations: 8,
      scale: 0.455,
      dotFactor: 0.54,
      vOffset: 1.5,
      intensityFactor: 0.21,
      expFactor: 6.2,
      redFactor: 0.5,
      greenFactor: 1.2,
      blueFactor: 1.9,
      colorShift: 0.8,
  },
  'Solar Flare': {
      speed: 2.2,
      iterations: 7,
      scale: 0.11,
      dotFactor: 0.32,
      vOffset: 10.0,
      intensityFactor: 0.12,
      expFactor: 12.0,
      redFactor: 1.8,
      greenFactor: 0.4,
      blueFactor: -0.4,
      colorShift: 0.0,
  },
  'Deep Ocean': {
      speed: 0.6,
      iterations: 12,
      scale: 0.25,
      dotFactor: 0.8,
      vOffset: 0.6,
      intensityFactor: 0.15,
      expFactor: 4.5,
      redFactor: -1.2,
      greenFactor: -0.2,
      blueFactor: 1.5,
      colorShift: 0.3,
  },
  'The Matrix': {
      speed: 1.2,
      iterations: 8,
      scale: 0.18,
      dotFactor: 0.75,
      vOffset: 0.9,
      intensityFactor: 0.22,
      expFactor: 6.0,
      redFactor: -1.5,
      greenFactor: 1.8,
      blueFactor: -1.5,
      colorShift: 0.1,
  },
  'Knot': {
      speed: 2.3,
      iterations: 4,
      scale: 0.04,
      dotFactor: 0.31,
      vOffset: 1.14,
      intensityFactor: 0.08,
      expFactor: 3.7,
      redFactor: 0.3,
      greenFactor: 0.0,
      blueFactor: 0.1,
      colorShift: 0,
  }
};